import { ModuleMeta } from '@/types';

export const MODULE_METADATA: ModuleMeta[] = [
  { key: 'sleep', nameEn: 'Sleep', nameFa: 'خواب', icon: '🛏️', color: '#6366f1', description: 'Track sleep quality and duration' },
  { key: 'exercise', nameEn: 'Exercise', nameFa: 'ورزش', icon: '🏋️', color: '#f43f5e', description: 'Monitor workouts and activity levels' },
  { key: 'skin', nameEn: 'Skin', nameFa: 'پوست', icon: '🧴', color: '#ec4899', description: 'Track skin health and routines' },
  { key: 'hair', nameEn: 'Hair', nameFa: 'مو', icon: '💇', color: '#8b5cf6', description: 'Monitor hair and scalp health' },
  { key: 'nutrition', nameEn: 'Nutrition', nameFa: 'تغذیه', icon: '🍎', color: '#22c55e', description: 'Log meals and track macros' },
  { key: 'supplements', nameEn: 'Supplements', nameFa: 'مکمل', icon: '💊', color: '#f97316', description: 'Track vitamin and supplement intake' },
  { key: 'water', nameEn: 'Water', nameFa: 'آب', icon: '💧', color: '#06b6d4', description: 'Monitor daily hydration' },
  { key: 'bloodTest', nameEn: 'Blood Test', nameFa: 'آزمایش خون', icon: '🩸', color: '#ef4444', description: 'Track biomarker levels' },
  { key: 'bmi', nameEn: 'BMI', nameFa: 'شاخص توده بدنی', icon: '⚖️', color: '#14b8a6', description: 'Body mass index tracking' },
  { key: 'calories', nameEn: 'Calories', nameFa: 'کالری', icon: '🔥', color: '#f59e0b', description: 'Calorie balance and BMR tracking' },
];

export const LOCALIZATION = {
  en: {
    // Nav
    home: 'Home',
    addEntry: 'Add Entry',
    settings: 'Settings',
    signIn: 'Sign In',
    signOut: 'Sign Out',
    // Hero
    heroTitle1: 'Your Health,',
    heroTitle2: 'Intelligently',
    heroTitle3: 'Analyzed',
    heroSubtitle: '10 interconnected health modules. Cross-module correlation analysis. Personalized AI insights powered by advanced language models.',
    heroCta: 'Generate AI Insights',
    heroCtaSecondary: 'Add Entry',
    // Stats
    statSleep: 'Sleep',
    statExercise: 'Exercise',
    statWater: 'Water',
    statBMI: 'BMI',
    statCalories: 'Calories',
    // Sections
    dashboard: 'Health Overview',
    dashboardSubtitle: 'Overview of all health modules',
    healthTrends: 'Health Trends',
    healthTrendsSubtitle: 'Visualize your progress over time',
    aiInsights: 'AI Health Insights',
    aiInsightsSubtitle: 'Cross-module correlation analysis',
    // AI Panel
    generateInsights: 'Generate AI Health Insights',
    healthScore: 'Health Score',
    criticalAlerts: 'Critical Alerts',
    weeklyPlan: 'Weekly Action Plan',
    moduleInsights: 'Module Insights',
    crossCorrelations: 'Cross-Module Correlations',
    noData: 'No data available',
    loading: 'Analyzing your health data...',
    error: 'Failed to analyze health data',
    excellent: 'Excellent',
    good: 'Good',
    fair: 'Fair',
    needsAttention: 'Needs Attention',
    improving: 'Improving',
    worsening: 'Worsening',
    stable: 'Stable',
    recommendation: 'Recommendation',
    priority: 'Priority',
    action: 'Action',
    deadline: 'Deadline',
    // Module names
    sleep: 'Sleep',
    exercise: 'Exercise',
    skin: 'Skin',
    hair: 'Hair',
    nutrition: 'Nutrition',
    supplements: 'Supplements',
    water: 'Water',
    bloodTest: 'Blood Test',
    bmi: 'BMI',
    calories: 'Calories',
    // Footer
    footerBrand: 'AI-powered health intelligence. 10 modules, cross-correlation analysis, personalized insights.',
    footerModules: 'Modules',
    footerQuickLinks: 'Quick Links',
    footerPoweredBy: 'Powered By',
    footerAddHealthEntry: 'Add Health Entry',
    footerProfileSettings: 'Profile & Settings',
    footerBuiltWith: 'Built with ❤️ for your health.',
    footerApiConnected: 'API Connected',
    // Charts
    chartSleep: 'Sleep Duration & Quality Trend',
    chartExercise: 'Exercise Sessions & Calories Burned',
    chartNutrition: "Today's Macronutrient Breakdown",
    chartWater: "Today's Hourly Water Intake",
    chartBMI: 'BMI History',
    chartCalories: 'Calorie Balance (Consumed vs Burned)',
    chartBloodtest: 'Latest Biomarker Status',
    // Profile
    profileTitle: 'Profile & Settings',
    personalInfo: 'Personal Information',
    name: 'Name',
    age: 'Age',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    other: 'Other',
    dateOfBirth: 'Date of Birth',
    preferences: 'Preferences',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    quickActions: 'Quick Actions',
    loadDemoData: 'Load Demo Data',
    loadDemoDesc: 'Populate all modules with sample data',
    saveProfile: 'Save Profile',
    saveProfileDesc: 'Persist your profile changes',
    saved: 'Saved!',
    apiConfig: 'API Configuration',
    model: 'Model',
    provider: 'Provider',
    streaming: 'Streaming',
    supported: 'Supported',
    userId: 'User ID',
    // Auth
    welcomeBack: 'Welcome Back',
    createAccount: 'Create Account',
    email: 'Email',
    password: 'Password',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    demoCredentials: 'Demo credentials',
    // Misc
    noRecords: 'No records',
    records: 'records',
    view: 'View',
    minutes: 'min',
    sessions: 'sessions',
    meals: 'meals',
    flags: 'flags',
    adherence: 'adherence',
    avg: 'avg',
    session: 'session',
    perWeek: '/week',
  },
  fa: {
    // Nav
    home: 'خانه',
    addEntry: 'افزودن رکورد',
    settings: 'تنظیمات',
    signIn: 'ورود',
    signOut: 'خروج',
    // Hero
    heroTitle1: 'سلامت شما،',
    heroTitle2: 'هوشمندانه',
    heroTitle3: 'تحلیل شده',
    heroSubtitle: '۱۰ ماژول سلامت به هم پیوسته. تحلیل همبستگی بین ماژولی. بینش‌های هوش مصنوعی شخصی‌سازی شده.',
    heroCta: 'تولید بینش هوش مصنوعی',
    heroCtaSecondary: 'افزودن رکورد',
    // Stats
    statSleep: 'خواب',
    statExercise: 'ورزش',
    statWater: 'آب',
    statBMI: 'شاخص توده',
    statCalories: 'کالری',
    // Sections
    dashboard: 'نمای کلی سلامت',
    dashboardSubtitle: 'مرور کلی همه ماژول‌های سلامت',
    healthTrends: 'روندهای سلامت',
    healthTrendsSubtitle: 'پیشرفت خود را در طول زمان ببینید',
    aiInsights: 'بینش‌های سلامت هوش مصنوعی',
    aiInsightsSubtitle: 'تحلیل همبستگی بین ماژولی',
    // AI Panel
    generateInsights: 'تولید بینش‌های سلامت هوش مصنوعی',
    healthScore: 'امتیاز سلامت',
    criticalAlerts: 'هشدارهای مهم',
    weeklyPlan: 'برنامه عمل هفتگی',
    moduleInsights: 'بینش‌های ماژول',
    crossCorrelations: 'همبستگی‌های بین ماژولی',
    noData: 'داده‌ای موجود نیست',
    loading: 'در حال تحلیل داده‌های سلامت شما...',
    error: 'خطا در تحلیل داده‌های سلامت',
    excellent: 'عالی',
    good: 'خوب',
    fair: 'متوسط',
    needsAttention: 'نیاز به توجه',
    improving: 'رو به بهبود',
    worsening: 'رو به وخامت',
    stable: 'پایدار',
    recommendation: 'توصیه',
    priority: 'اولویت',
    action: 'اقدام',
    deadline: 'مهلت',
    // Module names
    sleep: 'خواب',
    exercise: 'ورزش',
    skin: 'پوست',
    hair: 'مو',
    nutrition: 'تغذیه',
    supplements: 'مکمل',
    water: 'آب',
    bloodTest: 'آزمایش خون',
    bmi: 'شاخص توده بدنی',
    calories: 'کالری',
    // Footer
    footerBrand: 'هوش سلامت مبتنی بر هوش مصنوعی. ۱۰ ماژول، تحلیل همبستگی، بینش‌های شخصی.',
    footerModules: 'ماژول‌ها',
    footerQuickLinks: 'لینک‌های سریع',
    footerPoweredBy: 'قدرت گرفته از',
    footerAddHealthEntry: 'افزودن رکورد سلامت',
    footerProfileSettings: 'پروفایل و تنظیمات',
    footerBuiltWith: 'با ❤️ برای سلامت شما ساخته شده.',
    footerApiConnected: 'API متصل',
    // Charts
    chartSleep: 'روند مدت و کیفیت خواب',
    chartExercise: 'جلسات ورزش و کالری سوزانده شده',
    chartNutrition: 'ترکیب درشت‌غذایی امروز',
    chartWater: 'مصرف آب ساعتی امروز',
    chartBMI: 'تاریخچه شاخص توده بدنی',
    chartCalories: 'تعادل کالری (مصرف شده در مقابل سوزانده شده)',
    chartBloodtest: 'وضعیت آخرین نشانگرهای زیستی',
    // Profile
    profileTitle: 'پروفایل و تنظیمات',
    personalInfo: 'اطلاعات شخصی',
    name: 'نام',
    age: 'سن',
    gender: 'جنسیت',
    male: 'مرد',
    female: 'زن',
    other: 'دیگر',
    dateOfBirth: 'تاریخ تولد',
    preferences: 'ترجیحات',
    language: 'زبان',
    theme: 'پوسته',
    light: 'روشن',
    dark: 'تاریک',
    quickActions: 'اقدامات سریع',
    loadDemoData: 'بارگذاری داده نمونه',
    loadDemoDesc: 'پر کردن همه ماژول‌ها با داده نمونه',
    saveProfile: 'ذخیره پروفایل',
    saveProfileDesc: 'ذخیره تغییرات پروفایل شما',
    saved: 'ذخیره شد!',
    apiConfig: 'پیکربندی API',
    model: 'مدل',
    provider: 'ارائه‌دهنده',
    streaming: 'پخش جریانی',
    supported: 'پشتیبانی می‌شود',
    userId: 'شناسه کاربر',
    // Auth
    welcomeBack: 'خوش آمدید',
    createAccount: 'ایجاد حساب کاربری',
    email: 'ایمیل',
    password: 'رمز عبور',
    dontHaveAccount: 'حساب کاربری ندارید؟',
    alreadyHaveAccount: 'قبلاً حساب دارید؟',
    demoCredentials: 'اطلاعات ورود نمونه',
    // Misc
    noRecords: 'بدون رکورد',
    records: 'رکورد',
    view: 'مشاهده',
    minutes: 'دقیقه',
    sessions: 'جلسه',
    meals: 'وعده',
    flags: 'پرچم',
    adherence: 'پایبندی',
    avg: 'میانگین',
    session: 'جلسه',
    perWeek: '/هفته',
  },
} as const;

export type TranslationKey = keyof typeof LOCALIZATION.en;

export const API_CONFIG = {
  openRouterBaseUrl: 'https://openrouter.ai/api/v1',
  model: 'z-ai/glm-5.2',
  maxTokens: 4096,
  temperature: 0.7,
} as const;

export const HEALTH_RANGES = {
  sleep: { minHours: 7, maxHours: 9 },
  water: { minMl: 2000, recommendedMl: 3000 },
  bmi: {
    underweight: 18.5,
    normal: 24.9,
    overweight: 29.9,
  },
  restingHeartRate: { min: 50, max: 100 },
  steps: { sedentary: 5000, active: 10000, veryActive: 15000 },
} as const;
